# Generated by Django 5.2.8 on 2026-08-26 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_semanas', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, editable=False, null=True)),
                ('block_theme', models.CharField(blank=True, help_text='Objetivo principal das 12 semanas', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semana', models.IntegerField()),
                ('week_title', models.CharField(blank=True, help_text='Ex: Fim do Senac', max_length=100, null=True)),
                ('main_objective', models.TextField(blank=True, help_text='Micro-objetivo da semana', null=True)),
                ('is_milestone', models.BooleanField(default=False)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas', to='calendario.calendario')),
            ],
        ),
    ]
