# Generated by Django 5.2.8 on 2026-08-29 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcos', to='calendario.calendariosemana')),
            ],
        ),
    ]
