# Generated by Django 5.2.8 on 2026-08-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_marco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='quantidade_semanas',
            field=models.IntegerField(default=12),
        ),
    ]
