# Generated by Django 5.2.8 on 2026-08-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contador', '0002_calendario_block_theme_calendariosemana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendariosemana',
            name='calendario',
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
        migrations.DeleteModel(
            name='CalendarioSemana',
        ),
    ]
