# Generated by Django 6.0.6 on 2026-07-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('urlimagem', models.URLField()),
                ('lido', models.BooleanField(default=False)),
                ('data_leitura', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
