# Generated by Django 6.0.6 on 2026-07-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycontador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_semanas', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
