# Generated by Django 5.2.8 on 2026-07-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycontador', '0002_calendario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habitos',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='habitos',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='habitos',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='calendario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='habitos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
