# Generated by Django 6.0.6 on 2026-07-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycontador', '0003_rename_description_habitos_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('urlimagem', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='calendario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='habitos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
