# Generated by Django 6.0.6 on 2026-07-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mycontador', '0004_livros_alter_calendario_id_alter_habitos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='data_leitura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
