# Generated by Django 6.0.6 on 2026-07-30 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mycontador', '0005_livros_data_leitura_livros_lido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Livros',
        ),
    ]
