# Generated by Django 5.2.8 on 2026-08-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_semanas', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
