# Generated by Django 5.2.8 on 2026-08-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contador', '0003_remove_calendariosemana_calendario_delete_calendario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
